name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer
        extensions: mbstring, xml, ctype, iconv, dom, fileinfo

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Cache config and routes
      run: |
        php artisan config:cache
        php artisan route:cache

    - name: Run migrations
      run: php artisan migrate

    - name: Run tests
      run: php artisan test

    - name: Run tests
      run: php artisan test

    # ...existing code...

    - name: Send success webhook
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          await fetch('GOOGLE_WEBHOOK_URL', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              status: 'success',
              message: 'Laravel CI pipeline succeeded!',
              repo: context.repo.repo,
              branch: context.ref
            })
          });

    - name: Send failure webhook
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          await fetch('GOOGLE_WEBHOOK_URL', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              status: 'failure',
              message: 'Laravel CI pipeline failed!',
              repo: context.repo.repo,
              branch: context.ref
            })
          });
